platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


def all_main_targets_pods
    pod 'RxSwift', '4.2.0'
    pod 'RxCocoa'
end

target 'Rx-Playground' do
    all_main_targets_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
                                target.build_configurations.each do |config|
                                        config.build_settings['SWIFT_VERSION'] = '4.0'
                                end
    #List of exceptions
                        if ['Charts'].include? target.name
                                        target.build_configurations.each do |config|
                                                        config.build_settings['SWIFT_VERSION'] = '4.2'
                                                        end
                                        end
                        if ['SkeletonView'].include? target.name
                                target.build_configurations.each do |config|
                                        config.build_settings['SWIFT_VERSION'] = '5.0'
                                end
                        end
                end
end


